[package]
name = "dcs-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dcs-assembly = { path = "../dcs-assembly" }
dcs-blocks = { path = "../dcs-blocks" }
dcs-core = { path = "../dcs-core" }
dcs-model = { path = "../dcs-model" }
dcs-runtime = { path = "../dcs-runtime" }
serde_json = "1.0.151"
