[package]
name = "dcs-blocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dcs-core = { path = "../dcs-core" }
dcs-runtime = { path = "../dcs-runtime" }

[dev-dependencies]
dcs-model = { path = "../dcs-model" }
dcs-sim = { path = "../dcs-sim" }
